'use client';
import {useMemo,useState} from 'react';
import {checkAnswer,conditionLabel,enumerate,observation,ruleText,workedExample} from '@/lib/engine.mjs';
type Props={cards:number[];divisors:number[];length:number;accepted:string[];status:string;onSubmit:(value:string)=>Promise<string>;onNext?:()=>void;findAll?:boolean};
export default function Game({cards,divisors,length,accepted,status,onSubmit,onNext,findAll=false}:Props){
 const [value,setValue]=useState(''),[hint,setHint]=useState(0),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState('數卡準備好了，試試你的第一個答案！'),[tone,setTone]=useState('neutral');
 const solutions=useMemo(()=>enumerate(cards,length,divisors),[cards,length,divisors]);
 const example=solutions[0],target=findAll?solutions.length:3;
 const hintNames=['整除規則','觀察這組數卡','示範一個答案'];
 const hints=[ruleText(divisors),example?observation(cards,length,divisors,example):'',example?workedExample(example,divisors):''];
 const finished=accepted.length>=target,disabled=busy||finished||status!=='running';
 async function submit(){if(disabled)return;const result=checkAnswer(value,cards,length,divisors,accepted);if(!result.ok){setTone('retry');setFeedback(result.message);return;}setBusy(true);try{setFeedback(await onSubmit(result.value!));setTone('success');setValue('');}catch(error){setTone('retry');setFeedback(error instanceof Error?error.message:'未能儲存，請重試。');}finally{setBusy(false);}}
 return <div className="workspace"><section className="challenge panel" aria-labelledby="challenge-title"><div className="challenge-head"><div><p className="eyebrow">{divisors.length>=2?'多條件挑戰':'你的任務'}</p><h2 id="challenge-title">組成能被 {conditionLabel(divisors)} 整除的{length===3?'三':'四'}位數</h2></div><div className="goal"><strong>{accepted.length}</strong><span>/ {target} 個</span></div></div><p className="instructions">從下面選 {length} 張數卡，{findAll?`找出全部 ${target} 個不同答案。`:'找出 3 個不同答案。'}{divisors.length>=2&&<strong>所選條件必須全部同時符合。</strong>}</p>
 <div className="cards" aria-label="本回合的五張數卡">{cards.map(d=><button key={d} type="button" className={`number-card ${value.includes(String(d))?'chosen':''}`} aria-pressed={value.includes(String(d))} aria-label={`數卡 ${d}`} disabled={disabled||value.includes(String(d))||value.length>=length} onClick={()=>{setValue(v=>v+d);setTone('neutral');setFeedback('排好了嗎？點按「檢查答案」試一試。');}}>{d}</button>)}</div>
 <div className="builder"><div className="input-label"><label htmlFor="number-input">組合你的數字</label><span>每張卡只用一次</span></div><form className="entry-row" onSubmit={e=>{e.preventDefault();void submit();}}><input id="number-input" type="text" inputMode="numeric" maxLength={length} autoComplete="off" aria-describedby="entry-help feedback" placeholder={`輸入${length===3?'三':'四'}位數`} value={value} disabled={disabled} onChange={e=>{setValue(e.target.value);setTone('neutral');}}/><button type="submit" className="primary" disabled={disabled}>{busy?'儲存中…':'檢查答案'}</button></form><div className="entry-tools"><p id="entry-help">點選數卡，或直接輸入數字。首位不能是 0。</p><button type="button" disabled={disabled} onClick={()=>setValue(v=>v.slice(0,-1))}>退一格</button><button type="button" disabled={disabled} onClick={()=>setValue('')}>清空</button></div><p id="feedback" className={`feedback ${tone}`} role="status">{status==='paused'?'老師已暫停比賽，請等待繼續。':status==='ended'?'比賽已結束，你的答案已保留。':feedback}</p></div>
 <div className="answer-area"><div className="answer-title"><h3>我的答案</h3><span>{findAll?`已找到 ${accepted.length} 個，還差 ${Math.max(0,target-accepted.length)} 個`:'找到 3 個就完成'}</span></div><ol id="answers">{Array.from({length:findAll?Math.max(1,accepted.length):3},(_,i)=><li key={i} className={accepted[i]?'filled':''}><span className="answer-index">{i+1}</span><strong className={accepted[i]?'':'empty'}>{accepted[i]||'等待你的發現'}</strong>{accepted[i]&&<span className="answer-proof">{divisors.map(d=><span key={d}>÷ {d} = {Number(accepted[i])/d}<br/></span>)}</span>}</li>)}</ol></div>
 {finished&&<div className="completed"><div><strong>挑戰完成！</strong><p>{findAll?`你已找齊全部 ${target} 個符合條件的答案！`:onNext?'你找到了 3 個不同的答案。':'你已完成 3 個答案，老師可以查看你的結果。'}</p></div>{onNext&&<button className="primary" onClick={onNext}>再挑戰一回合</button>}</div>}</section>
 <aside className="hints panel"><div className="hint-head"><span className="hint-symbol" aria-hidden="true">?</span><div><p className="eyebrow">按需要查看</p><h2>我的提示工具</h2></div></div><p className="hint-intro">先自己想一想。需要幫忙時，每次揭開一個提示。</p><ol className="hint-list">{hintNames.map((name,i)=><li key={i} className={i<hint?'revealed':'locked'}><h3>0{i+1}　{name}</h3><p>{i<hint?hints[i]:'點按下方按鈕，逐步揭開提示。'}</p></li>)}</ol><button type="button" className="hint-button" disabled={hint===3||status!=='running'} onClick={()=>setHint(h=>h+1)}>{hint===3?'三個提示已全部揭開':`查看提示 ${hint+1}：${hintNames[hint]}`}</button><p className="hint-foot">使用提示也可以完成挑戰。<br/>試著把方法用在下一個答案！</p></aside></div>;
}
