'use client';
import {useEffect,useRef,useState} from 'react';
import Game from './game';
import {conditionLabel,generatePracticeRound,checkAnswer} from '@/lib/engine.mjs';
import {api,statuses,TEACHER_URL,type StudentState} from '@/lib/types';
export default function StudentApp(){
 const [mode,setMode]=useState<'practice'|'competition'>('practice'),[divisors,setDivisors]=useState<number[]>([2,3]),[length,setLength]=useState(3),[practice,setPractice]=useState<{cards:number[];id:number}|null>(null),[accepted,setAccepted]=useState<string[]>([]),[student,setStudent]=useState<StudentState|null>(null),[code,setCode]=useState(''),[nickname,setNickname]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[syncError,setSyncError]=useState('');
 const serial=useRef(0),generation=useRef(0),inFlight=useRef(false);
 function newPractice(ds=divisors,l=length){setPractice(ds.length>=2?{cards:generatePracticeRound(ds,l).cards,id:++serial.current}:null);setAccepted([]);}
 function toggleCondition(d:number){const next=divisors.includes(d)?divisors.filter(x=>x!==d):[...divisors,d].sort((a,b)=>a-b);setDivisors(next);newPractice(next,length);}
 useEffect(()=>{setPractice({cards:generatePracticeRound([2,3],3).cards,id:++serial.current});const c=new URL(window.location.href).searchParams.get('code');if(c){setMode('competition');setCode(c.toUpperCase());}void api<StudentState>('/api/student/state').then(data=>{if(!c||data.competition.code===c.toUpperCase()){setStudent(data);setMode('competition');}else{setNickname(data.nickname);}}).catch(()=>{});},[]);
 useEffect(()=>{if(!student)return;let active=true;const poll=async()=>{if(inFlight.current)return;const version=generation.current;try{const data=await api<StudentState>('/api/student/state');if(active&&version===generation.current){setStudent(data);setSyncError('');}}catch(error){if(active)setSyncError(error instanceof Error?error.message:'未能同步，請檢查連線。');}};const timer=setInterval(()=>void poll(),4000);return()=>{active=false;clearInterval(timer);};},[student?.competition.id]);
 async function join(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{generation.current++;setStudent(await api<StudentState>('/api/student/join',{code,nickname}));setSyncError('');}catch(error){setMessage(error instanceof Error?error.message:'未能加入，請重試。');}finally{setBusy(false);}}
 async function submitCompetition(value:string){inFlight.current=true;generation.current++;try{const data=await api<StudentState & {message:string}>('/api/student/answer',{value});setStudent(data);setSyncError('');return data.message;}finally{inFlight.current=false;}}
 async function leave(){setBusy(true);try{await api('/api/student/leave',{});generation.current++;setStudent(null);setMessage('');setSyncError('');}catch(error){setSyncError(error instanceof Error?error.message:'未能退出。');}finally{setBusy(false);}}
 return <div className="page"><header><div className="brandmark" aria-hidden="true">÷</div><div><p className="eyebrow">數學探索室</p><h1>數卡整除挑戰</h1></div><a className="teacher-link" href={TEACHER_URL} target="_top">老師控制台</a></header><nav className="mode-tabs" aria-label="活動模式"><button aria-pressed={mode==='practice'} onClick={()=>setMode('practice')}>自由練習</button><button aria-pressed={mode==='competition'} onClick={()=>setMode('competition')}>加入老師比賽</button></nav>
 {mode==='practice'?<><section className="settings" aria-label="選擇挑戰"><div><p className="setting-label">整除條件（至少選兩項，已選 {divisors.length} 項）</p><div className="segmented">{[2,3,5,10].map(d=><button key={d} aria-pressed={divisors.includes(d)} onClick={()=>toggleCondition(d)}>÷ {d}</button>)}</div></div><div><p className="setting-label">組成幾位數？</p><div className="segmented size-choice">{[3,4].map(l=><button key={l} aria-pressed={length===l} onClick={()=>{setLength(l);newPractice(divisors,l);}}>{l===3?'三':'四'}位數</button>)}</div></div><button className="new-cards" disabled={divisors.length<2} onClick={()=>newPractice()}>換一組數卡 ↻</button></section>{practice?<Game key={practice.id} cards={practice.cards} divisors={divisors} findAll length={length} accepted={accepted} status="running" onNext={()=>newPractice()} onSubmit={async value=>{const result=checkAnswer(value,practice.cards,length,divisors,accepted);if(!result.ok)throw new Error(result.message);setAccepted(a=>[...a,result.value!]);return result.message;}}/>:<p className="panel loading" role="status">{divisors.length<2?'請至少選擇兩項整除條件，才可以開始自由練習。':'正在準備數卡…'}</p>}<p className="footer-note">同一組數卡可以重新排列，組成另一個答案。切換條件或位數會開始新回合。</p></>:<>
 {!student?<section className="join-panel panel"><p className="eyebrow">全班一起挑戰</p><h2>加入老師派發的比賽</h2><p className="instructions">輸入老師的參賽代碼。大家使用相同的 5 張數卡，找出同時符合兩項整除條件的 3 個答案。</p><form onSubmit={join} className="join-form"><label htmlFor="join-code">參賽代碼<input id="join-code" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} maxLength={6} placeholder="例如 AB3K7P" autoCapitalize="characters" autoComplete="off" required/></label><label htmlFor="nickname">參賽名稱<input id="nickname" value={nickname} onChange={e=>setNickname(e.target.value)} maxLength={24} placeholder="例如 4A 12" required/></label><button className="primary" disabled={busy}>{busy?'加入中…':'加入比賽'}</button></form><p role="status" className="feedback retry">{message||'加入後，等老師開始便可以作答。'}</p></section>:<>
 <div className="competition-banner"><div><p className="eyebrow">參賽代碼 {student.competition.code} · {student.nickname}</p><h2>{statuses[student.competition.status]}</h2><p>同時能被 <strong>{conditionLabel(student.competition.divisors)}</strong> 整除 · {student.competition.length===3?'三':'四'}位數</p></div><button className="new-cards" disabled={busy} onClick={()=>void leave()}>退出比賽</button></div>
 {syncError&&<div className="connection-error" role="alert">{syncError}　連線恢復後會自動同步；請保留目前畫面。</div>}
 {student.competition.status==='waiting'?<section className="panel waiting-room"><div className="waiting-symbol" aria-hidden="true">⋯</div><h2>你已加入比賽！</h2><p>老師按下「開始比賽」後，數卡便會出現。</p><p>記住：同時符合兩項條件，才算答對。</p></section>:<Game key={student.competition.id} cards={student.competition.cards} divisors={student.competition.divisors} length={student.competition.length} accepted={student.accepted} status={syncError?'offline':student.competition.status} onSubmit={submitCompetition}/>}</>}
 </>}
 </div>;
}
