'use client';
import {useEffect,useRef,useState} from 'react';
import {conditionLabel,generateRound} from '@/lib/engine.mjs';
import {api,statuses,type Competition,type Participant} from '@/lib/types';
export default function TeacherPanel({studentUrl}:{studentUrl?:string}){
 const [divisors,setDivisors]=useState([2,3]),[length,setLength]=useState(3),[cards,setCards]=useState<number[]>([]),[competitions,setCompetitions]=useState<Competition[]>([]),[selected,setSelected]=useState<string|null>(null),[current,setCurrent]=useState<{competition:Competition;participants:Participant[]}|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[confirmEnd,setConfirmEnd]=useState(false);
 const requestGeneration=useRef(0),inFlight=useRef(false);
 async function refresh(){const data=await api<{competitions:Competition[]}>('/api/teacher/competitions');setCompetitions(data.competitions);return data.competitions as Competition[];}
 useEffect(()=>{setCards(generateRound([2,3],3).cards);void refresh().then(list=>{if(list.length)setSelected(list[0].id);}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!selected){setCurrent(null);return;}let active=true;setCurrent(null);setConfirmEnd(false);requestGeneration.current++;const poll=async()=>{if(inFlight.current)return;const version=requestGeneration.current;try{const data=await api<{competition:Competition;participants:Participant[]}>(`/api/teacher/competitions/${selected}`);if(active&&version===requestGeneration.current){setCurrent(data);setError('');setCompetitions(cs=>cs.map(c=>c.id===data.competition.id?data.competition:c));}}catch(e){if(active)setError(e instanceof Error?e.message:'未能同步。');}};void poll();const timer=setInterval(()=>void poll(),4000);return()=>{active=false;clearInterval(timer);};},[selected]);
 function changePair(d:number){const next=divisors.includes(d)?divisors.filter(x=>x!==d):divisors.length<2?[...divisors,d].sort((a,b)=>a-b):divisors;setDivisors(next);setCards(next.length===2?generateRound(next,length).cards:[]);setMessage('');}
 async function create(){if(divisors.length!==2)return;setBusy(true);setError('');try{const data=await api<{competition:Competition}>('/api/teacher/competitions',{divisors,length,cards});await refresh();setSelected(data.competition.id);setMessage('比賽已派發。把參賽代碼告訴學生，待他們加入後按「開始比賽」。');}catch(e){setError(e instanceof Error?e.message:'未能派發。');}finally{setBusy(false);}}
 async function changeStatus(status:string){if(!selected)return;setBusy(true);inFlight.current=true;requestGeneration.current++;try{await api(`/api/teacher/competitions/${selected}`,{status});const data=await api<{competition:Competition;participants:Participant[]}>(`/api/teacher/competitions/${selected}`);setCurrent(data);setCompetitions(cs=>cs.map(c=>c.id===selected?data.competition:c));setConfirmEnd(false);setError('');}catch(e){setError(e instanceof Error?e.message:'未能更改比賽。');}finally{setBusy(false);inFlight.current=false;}}
 async function copyLink(){if(!current)return;const url=new URL(studentUrl||window.location.origin);url.searchParams.set('code',current.competition.code);const link=url.toString();try{await navigator.clipboard.writeText(link);setMessage('學生加入連結已複製。');}catch{setMessage(`學生加入連結：${link}`);}}
 return <div className="page"><header><div className="brandmark" aria-hidden="true">÷</div><div><p className="eyebrow">老師專用</p><h1>比賽控制台</h1></div><a href="/" className="teacher-link">學生入口</a></header><div className="teacher-workspace"><section className="panel create-panel"><p className="eyebrow">派發新比賽</p><h2>設定雙條件挑戰</h2><p className="instructions">先選兩項整除條件。學生使用同一組 5 張數卡，找出 3 個同時符合條件的答案。</p><p className="setting-label space-top">兩項整除條件（{divisors.length}/2）</p><div className="condition-picker">{[2,3,5,10].map(d=><button key={d} aria-pressed={divisors.includes(d)} disabled={busy||(!divisors.includes(d)&&divisors.length===2)} onClick={()=>changePair(d)}>÷ {d}</button>)}</div><p className="small-note">要改選條件，先取消其中一項。</p><p className="setting-label space-top">組成幾位數？</p><div className="segmented size-choice">{[3,4].map(l=><button key={l} aria-pressed={length===l} disabled={busy} onClick={()=>{setLength(l);setCards(divisors.length===2?generateRound(divisors,l).cards:[]);}}>{l===3?'三':'四'}位數</button>)}</div><div className="preview-head"><h3>本場比賽數卡</h3><button className="text-button" disabled={busy||divisors.length!==2} onClick={()=>setCards(generateRound(divisors,length).cards)}>換一組</button></div><div className="cards preview-cards">{cards.length?cards.map(d=><span className="number-card" key={d}>{d}</span>):<p className="small-note">選好兩項條件後會顯示數卡。</p>}</div><p className="small-note">每組數卡均有至少 3 個有效答案。派發後，這場比賽的題目便會固定。</p><button className="primary full-width" disabled={busy||divisors.length!==2||cards.length!==5} onClick={()=>void create()}>{busy?'處理中…':'派發比賽'}</button></section>
 <section className="panel manage-panel"><div className="manage-heading"><div><p className="eyebrow">全班同步</p><h2>控制已派發的比賽</h2></div><button className="text-button" disabled={busy} onClick={()=>void refresh().catch(e=>setError(e.message))}>重新整理</button></div><label className="contest-select">選擇比賽<select value={selected||''} onChange={e=>setSelected(e.target.value)} disabled={busy}><option value="" disabled>尚未派發比賽</option>{competitions.map(c=><option key={c.id} value={c.id}>{c.code} · ÷ {c.divisors.join('、')} · {statuses[c.status]}</option>)}</select></label>
 {current?<><div className="dispatch-box"><div><p>參賽代碼</p><strong className="join-code">{current.competition.code}</strong></div><button className="new-cards" onClick={()=>void copyLink()}>複製學生連結</button></div><div className="contest-summary"><span className={`status-pill ${current.competition.status}`}>{statuses[current.competition.status]}</span><p>同時能被 <strong>{conditionLabel(current.competition.divisors)}</strong> 整除 · {current.competition.length===3?'三':'四'}位數</p><div className="mini-cards">{current.competition.cards.map(d=><span key={d}>{d}</span>)}</div></div><div className="teacher-controls">{current.competition.status==='waiting'&&<button className="primary" disabled={busy} onClick={()=>void changeStatus('running')}>開始比賽</button>}{current.competition.status==='running'&&<button className="primary" disabled={busy} onClick={()=>void changeStatus('paused')}>暫停比賽</button>}{current.competition.status==='paused'&&<button className="primary" disabled={busy} onClick={()=>void changeStatus('running')}>繼續比賽</button>}{current.competition.status!=='ended'&&<button className="end-button" disabled={busy} onClick={()=>setConfirmEnd(true)}>結束比賽</button>}</div>{confirmEnd&&<div className="end-confirm"><p>結束後，學生不能再提交；已有答案會保留。</p><button className="end-button" disabled={busy} onClick={()=>void changeStatus('ended')}>確認結束</button><button className="text-button" onClick={()=>setConfirmEnd(false)}>繼續比賽</button></div>}<div className="progress-heading"><h3>參賽進度</h3><span>{current.participants.length} 人加入 · {current.participants.filter(p=>p.answers.length>=3).length} 人完成</span></div><div className="table-scroll"><table><thead><tr><th>參賽名稱</th><th>進度</th><th>已找到的答案</th></tr></thead><tbody>{current.participants.map(p=><tr key={p.id}><td>{p.nickname}</td><td><span className={p.answers.length===3?'done-label':''}>{p.answers.length}/3 {p.answers.length===3?'完成':''}</span></td><td>{p.answers.length?p.answers.join('、'):'尚未提交'}</td></tr>)}</tbody></table></div>{!current.participants.length&&<p className="empty-state">尚未有學生加入。把代碼告訴學生，或派發學生加入連結。</p>}<p className="small-note">每 4 秒自動同步。暫停或結束後，網站會停止接受新答案。</p></>:<p className="empty-state">{selected?'正在載入比賽…':'先在左側派發一場比賽。'}</p>}
 </section></div>{error&&<p role="alert" className="connection-error">{error}</p>}{message&&<p role="status" className="teacher-message">{message}</p>}</div>;
}
